spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/glovo
spring.datasource.username=postgres
spring.datasource.password=AD24683a
spring.jpa.hibernate.ddl-auto=update
spring.docker.compose.enabled=false